name: CI

on:
  workflow_dispatch:
    inputs:
      kernel-branch:
        required: true
        type: string
      release-type:
        required: true
        type: choice
        options:
        - kaihatsu
        - seishiki
        default: 'kaihatsu'

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Display parameters
        uses: m-s-abeer/update-gha-summary-with-workflow-inputs@v1

      - name: Build
        uses: frstprjkt/kernel_build_action@main
        with:
          kernel-url: https://github.com/nothing404error/kernel_xiaomi_chime.git
          kernel-branch: ${{ github.event.inputs.kernel-branch }}
          config: vendor/xiaomi/bengal_defconfig vendor/xiaomi/chime.config
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r563880
          anykernel3: true
          anykernel3-url: https://github.com/frstprjkt/AnyKernel3
          extra-cmd: LLVM=1 LLVM_IAS=1 KBUILD_BUILD_USER=Interstellar
          custom-package-name: Interstellar_$(date +%d%H%M)_chime-${{ github.event.inputs.release-type }}
